spring.application.name=sms

# Database Connection Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/sms_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger
springdoc.swagger-ui.path=/swagger-ui/index.html

#--------JWT configuration---------
jwt.algorithm.key=qwertyuiopasdfghjklzxvbnm
jwt.issuer=tushar
jwt.expiry.duration=86400000

#----------------Data.sql----------

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

#Logging property

#logging.level.com.sms=INFO
#logging.level.root=DEBUG
